#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(cd .. && pwd)"

localWorkspaceFolder="${1:-$REPO_ROOT}"
containerWorkspaceFolder="${2:-/home/vscode/$(basename "$REPO_ROOT")}"
localWorkspaceFolderBasename="${3:-$(basename "$REPO_ROOT")}"
containerWorkspaceFolderBasename="${4:-$(basename "$REPO_ROOT")}"
workspaceSlug="$(printf '%s' "$localWorkspaceFolderBasename" \
  | tr '[:upper:]' '[:lower:]' \
  | sed -E 's/[^a-z0-9_.-]+/-/g; s/^-+//; s/-+$//')"
if [ -z "$workspaceSlug" ]; then
  workspaceSlug="workspace"
fi
aiStateVolumePrefix="${workspaceSlug}-ai-state"

CLAUDE_CODE_VERSION=
CODEX_CLI_VERSION=
if [ -f .env.example ]; then
  # shellcheck disable=SC1091
  source .env.example
fi
if [ -z "${CLAUDE_CODE_VERSION}" ] || [ -z "${CODEX_CLI_VERSION}" ]; then
  echo "ERROR: set CLAUDE_CODE_VERSION and CODEX_CLI_VERSION in .devcontainer/.env.example" >&2
  exit 1
fi

cat > .env <<EOF
# Generated by initializeCommand.sh — do not commit

localWorkspaceFolder=${localWorkspaceFolder}
containerWorkspaceFolder=${containerWorkspaceFolder}
localWorkspaceFolderBasename=${localWorkspaceFolderBasename}
containerWorkspaceFolderBasename=${containerWorkspaceFolderBasename}
aiStateVolumePrefix=${aiStateVolumePrefix}

CLAUDE_CODE_VERSION=${CLAUDE_CODE_VERSION}
CODEX_CLI_VERSION=${CODEX_CLI_VERSION}
EOF

echo "Wrote .devcontainer/.env (containerWorkspaceFolder=${containerWorkspaceFolder}, aiStateVolumePrefix=${aiStateVolumePrefix})"
